version: '3'

services:
  # Backend (Node.js)
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - NODE_ENV= development
      - PORT=5000
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - mongodb
    restart: always
    volumes:
      - ./backend:/app/backend 

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend
    restart: always

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - frontend
      - backend
    restart: always
    

  # MongoDB (Optional, if your backend uses MongoDB)
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
